# -*- coding: utf-8 -*-
"""List(tusar sir).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCY6pvYKWcumYIxqjHXeVGPM3815ngWI

DATA TYPE sequence data type (LIST):
- List: collection multiple element together
- similar array
- kisi bi datatype value ko stor kar sakte hai (heterozygous )
- square bracket []
- index start 0
- list are mutuable = change/update delete/insert
"""

a= [10,500,"abc"]
print(a,type(a))

mylist=[10,20,30,40]
print(mylist[0:5:3])

mylist=[10,20,30,40]
mylist[0]=86
mylist.append(1000) #insert at last,only one element
mylist.extend("krishan")      # extend acsses itreable value(list,string,tuple,dic,sets)=asa data jis pe for loop chala sakte hai
mylist.extend([100,400,'hey'])
print(mylist)

mylist=[10,20,30,40]
dir(mylist)  #function list ha type janne ke liye

mylist=[10,20,30,40]
mylist.pop()   #by defult last value delete, a=mylist.pop(0) stor bhi kar sakte hai
print(mylist)

mylist=[10,20,56,43,23,30,40]
mylist.sort()
print(mylist)
mylist.sort(reverse = True)
print(mylist)

"""Find the minimum element in a list without using inbuilt functions."""

mylist=[100,500,600,400,40,30]
mylist.sort()
print(mylist ,"mini value",mylist[0])

#method 2
mylist=[100,500,600,400,40,30]
mini=mylist[0]
for i in mylist:
  if mini>i:
    mini=i
print("minium value: ",mini)

"""Write a Python program to find the maximum element in a list without using inbuilt functions."""

mylist=[100,500,600,400,40,30]
max=mylist[0]
for i in mylist:
  if i>max:
    max=i
print(max)

"""Write a Python program to find all elements in a list that are divisible by 5 and store them in a new list."""

mylist=[100,500,600,34,56,78,400,40,30]
newlist=[]
for i in mylist:
  if i%5==0:
    newlist.append(i)
print(newlist)

mylist=[100,500,600,34,56,78,400,40,30]
for i in range(0,len(mylist)):
  print(i,mylist[i])

"""Write a Python program to find and print duplicate elements in a list using a while loop."""

mylist=[123,500,60,400,40,500,1012,123]
#dupilicat value
#1. list uniqw
uniqelist=[]
duplist=[]
for i in mylist:
  if i not in uniqelist:
    uniqelist.append(i)
  else:
    duplist.append(i)
print(duplist)

"""Write a Python program to find and print duplicate elements in a list using a while loop."""

mylist=[123,500,60,400,40,500,1012,123,60]
duplist=[]
uniqlist=[]
start=0
end=len(mylist)-1
while(start<end):
  if mylist[start]==mylist[end]:
    print("start",mylist[start],"end",mylist[end])
    duplist.append(mylist[start])

  end-=1


  if end==start:
    end=len(mylist)-1
    start +=1

print("duplicat list:",duplist)

"""Write a Python program to find all pairs of numbers in a list whose sum is equal to 9.

mylist=[1,2,4,7,14,17,32]

"""

mylist=[1,2,4,7,14,17,32]
list9=[]
start=0
end=len(mylist)-1
while(start<end):
  if mylist[start]+mylist[end]==9:
    print("start",mylist[start],"end",mylist[end])
    list9.extend([mylist[start],mylist[end]])
    #list9.append(mylist[end])

print("tow add 9:",list9)

"""Write a Python program to find the maximum profit that can be earned by buying and selling a stock once, given a list of stock prices.

mylist=[10,3,7,14,13]
"""

mylist=[10,3,7,14,13]
maxdiff=0
start=0
end=len(mylist)-1
while(start<end):
  if maxdiff<mylist[end]-mylist[start]:
    maxdiff=mylist[end]-mylist[start]
  end-=1
  if end==start:
    end=len(mylist)-1
    start +=1
print("max profit sell :",maxdiff)

"""Write a Python program to find all pairs of numbers in a list whose sum is equal to 14."""

mylist=[2,4,5,7,9,13,16]
list14=[]
start=0
end=len(mylist)-1
while(start<end):
  if mylist[start]+mylist[end]==14:
    print("start",mylist[start],"end",mylist[end])
    # break
    list14.append(mylist[(start)])
    list14.append(mylist[end])
    break
  end-=1
  if end==start:
    end=len(mylist)-1
    start +=1

print("tow add 14:",list14)

"""Write a Python program to find all triplets in a list whose sum is equal to 30 using the two‑pointer technique."""

#method 1.
mylist = [2,4,5,7,9,13,16]
for i in range(len(mylist)):
  for j in range(i+1,len(mylist)):
    for k in range(j+1,len(mylist)):
      if mylist[i]+mylist[j]+mylist[k]==30:
        print(mylist[i],mylist[j],mylist[k])

"""Write a Python program to find all triplets in a list whose sum is equal to 30 using the two‑pointer technique."""

#method 2.
mylist = [2,4,5,7,9,13,16]
i=0
while i< len(mylist):
  secnd = i+1
  while secnd <len(mylist):
    third= secnd+1
    while third <len(mylist):
      if mylist[i]+mylist[secnd]+mylist[third]==30:
        print(mylist[i],mylist[secnd],mylist[third])
      third +=1
    secnd +=1
  i +=1

"""Write a Python program to find all triplets in a list whose sum is equal to 30 using the two‑pointer technique."""

#method 3.
mylist = [2,4,5,7,9,13,16]
for i in range(len(mylist)):
  start=i+1
  end=len(mylist)-1
  while start<end:
    sum = mylist[i]+mylist[start]+mylist[end]
    if sum==30:
      print(mylist[i],mylist[start],mylist[end])
      start +=1
      end -=1
    elif sum<30:
      start +=1
    else:
      end -=1

"""list comprehension :-
[expression for item in iterable if condition]
"""

[i for i in range(1,10)]

newlist=[i**2 for i in range(1,10)]
print(newlist)

newlist=[i**2 for i in range(1,10) if i%2==0]
print(newlist)

"""for Nested loop:-

"""

[(i,j) for i in range(1,6) for j in range(5,7)]

"""Write a Python program that creates a list of lists, where each inner list contains a single number from 5 to 9."""

#[[5],[6],[7],[8],[9]]
newlist = []
for i in range(5,10):
  templist =[]
  templist.append(i)
  newlist.append(templist)
print(newlist)

"""Write a Python program to generate a nested list (list of lists) where each inner list contains sequential numbers starting from 5, with lengths increasing in each iteration."""

#[[5],[6,7],[8,9,10]]
x=5
newlist = []
for i in range(1,4):
  templist=[]     #recreating the templist again and again
  for j in range(1,i+1):
    templist.append(x)   # adding number s,  6,7 into the temp list
    x+=1
  newlist.append(templist)   #append the temp list to original list
  print(" ")
print(newlist)

"""Write a Python program to generate a nested list (list of lists) where each inner list contains numbers starting from 1 up to the current iteration count.

[[1],[1,2],[1,2,3],[1,2,3,4]]

[[1],[1,2],[1,*,3],[1,*,*,4],[1,*,*,*,5]]
"""

mylist=[]
for i in range(1,5):
  templist=[]
  for j in range(1,i+1):
    templist.append(j)
  mylist.append(templist)
  print()
print(mylist)

"""Write a Python program to generate a triangular pattern of numbers where the first and last positions are numbers, the diagonal is numbers, and the remaining positions are filled with *. Also store the pattern in a nested list.
1

1 2

1 * 3

1 * * 4

1 2 3 4 5
"""

mylist=[]
for i in range(1,6):
  templist=[]
  for j in range(1,i+1):
    if i==j or j==1 or i==5:
      print(j,end=" ")
      templist.append(j)
    else:
      print("*",end=" ")
      templist.append('*')
  mylist.append(templist)
  print()
print(mylist)

