# -*- coding: utf-8 -*-
"""function_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196AXb4-8ySvGETACZxl_nPGAgcN4OuEo

- Function:-

- - block of code that performs a spicific task
- - code reusability,modularity,easy maintenance
- - use:=
- - - Avoid repetitiopn of code
- - - improve readability
- - - make programs
- - - easy debugging and testing
"""

def hello():
  print("hello rohan")
  x=10
  print("hello gf",x)
hello()

def evenChack():
  x=int(input("Enter Number: "))
  if(x%2==0):
    print("Even")
  else:
    print("odd")
evenChack()

def prime():
  x=int(input("Enter Number: "))
  is_prime=True
  i=2
  while(i<x):
    if x%i==0:
      is_prime=False
    i+=1
  if is_prime:
    print("Prime number")
  else:
    print("not prime number")
prime()

def requestNotification(z,friendName):   #z=is called parameter
  print("hii user",z,"you got a friend request",friendName)

#outside function
userName=input("Enter username: ")
friend=input("Enter name")
requestNotification(userName,friend)   # unserName= argument

age=20  # global scope
def add_two_number(a,b):
  c=a+b     #local scope/variable
  print("total: ",c,"age: ",age)
add_two_number(15,60)

x=100
y=98
print("x and y id :",id(x),id(y))

def add_two_num(a,b):
  c=a+b
  print("memory a and b: ",id(a),id(b))
add_two_num(x,y)

x=100
y=98
print("x and y id :",id(x),id(y))

def add_two_num(a,b):
  a=87
  c=a+b
  print(" after update memory a and b: ",id(a),id(b))
  print("sum: ",c)
add_two_num(x,y)

count=0
def function_add(a,b):
  global count   # function me change karne ke liye batana padega ki global ha or ye first line me hi aayega.
  c=a+b
  count+=1
  print("c value: ",c,"count::",count)
function_add(10,40)
function_add(34,89)
print("count:::",count)

"""prime number chack"""

def check_prime(num):
  count=0
  for i in range(2,num//2+1):
    if num%i==0:
      count+=1
      break
  if count==0 and num!=1:
    print("prime")
  else:
    print("not prime")
check_prime(int(input("Enter number: ")))

"""- function type of argument passing"""

def function_param(studentname,age,fee=500): # fee=500 by default argument ke liye
  print(f"Name:{studentname}, age:{age}, fee: {fee}")
#function_param() #Error dega because no argument is passed

#position argument
function_param("krishsan",23,40000) #position argument
function_param("rohan",30000,23) #will give some diff result

#keyword argument(**kwargs)
function_param(fee=55000,age=34,studentname="tusar")   # key word deke data pass karna

#default argument
function_param("dakkan",32) # fee ki by default value lega ye function declar ke time banaya jata ha
function_param(age=45,studentname="dakkan")
function_param("dakkan",12,10001)


#variable length argument (*args)
def function_param1(*num):
  print(num,type(num))
  print(num)
function_param1(10)
function_param1(12,34,56,78,34,56,632,21)

"""class keyword +variable argument"""

def fun_keyvar(**k):
  print(k,type(k))
 # print(f"Name:{k['name']},age={k['age']},batch={k["btch"]},amount={k['amu']},address={k["add"]}")
fun_keyvar(name="krishan",age=34,btch="s",amu=4000)
fun_keyvar(age=45,name='rohan',btch='h',amu=90000)

def addNo(num):
  print(num+20)

x=addNo(80)
print("X values: ",x)

def addNo(num):
  print(num+20)
  return num+20   # return karege tabhi x ki value print hogi nhi to None aayega


x=addNo(80)
print("X values: ",x)

"""first class function:-"""

def func():
  print("Hello")
x=func
print("X values:",x,func)  # x and func ki memoery address same hoga
func()
x()

def samplefunc():
  print("regex software")
y=samplefunc()
mylist=[10,20,30,samplefunc]
mylist[-1]()
mylist[2]

def add_two_num(a,b):
  print(a+b)
def add_num(x,y):
  print("x:",x,"y: ",y)  # y ki value none hogi because add_two_num me retrun nhi h
add_num(90,add_two_num(30,50))
out=add_two_num(20,10)
print("out values: ",out)

def add_two_num(a,b):
  return(a+b)
def add_num(x,y):
  print("x:",x,"y: ",y)
  print(y(20,30))
add_num(90,add_two_num) # function ka () nhi dete ha to uska memory addres print hoga ,y ko meerory mila ha to y se function ko chal sakte hahi

out=add_two_num(20,10)
print("out values: ",out)

"""lambda function:-
- annoynous function
- same as like normal function
- start with lambda keyword
-  annymous function bcz thry dont have a name
- used to made code readable
- 1 line function // syntax is small// use and throw

syntax:-

lambda parameter1,p2,p3..........: expression

lambda               parameter              : expression

"""

print(lambda num:num*num)

a=lambda num:num*num # first class function

#a(8)
print(a(9))



"""class A25 and a24"""

del sum

student={"krishan":[10,20,30,40], "yash":[90,87,5,98]}

def avglist(newlist):
  print("avg:",sum(newlist)/len(newlist))

for i in student:
  print(i,student[i]) #printing dictionary value
  avglist(student[i]) #calling function

student={"krishan":[10,20,30,40], "yash":[90,87,5,98]}


for i in student:
  print(i,student[i]) #printing dictionary value
  #avglist(student[i]) # calling function
  b_lambda=lambda num: sum(num)/len(num)
  print("labbda output: ",b_lambda(student[i]))

b=lambda num: num*num
print(a(int(input())))

mylist=[10,34,56,23]
newlist=[]

for i in mylist:
  b= lambda num: num*num
  print(b(i))
  newlist.append(b(i))
print(newlist)

"""map() and filter():-
- high order function
"""

mylist=["hey","hello"]
x=map(len,["hey","hello"])
print(next(x))
print(next(x))

def prime(x):
  # x=int(input("Enter Number: "))
  is_prime=True
  i=2
  while(i<x):
    if x%i==0:
      is_prime=False
    i+=1
  if is_prime:
    print("Prime number")
  else:
    print("not prime number")
c=map(prime,[23,45,67,89])
print(next(c))
print(next(c))

def cube(n):
  return n*n*n

c=map(cube,[6,8,7,6,23,90])
print("c:",c)
print("1: ",next(c))
print("2: ",next(c))

c=map(lambda n: n*n*n,[6,8,7,6,23,90])
print("c:",c)
print("1: ",next(c))
print("2: ",next(c))

w=map(lambda n: n*n*n,range(1,10))
print(next(w))
print(w.__next__())

print(list(map(lambda n: n*n*n,range(1,10))))

print(tuple(map(lambda n: n*n*n,range(1,10))))

print(tuple(map(lambda a: a%2 !=0,(5,10,45,6,80,92))))

print(tuple(filter(lambda a: a%2 !=0,(5,10,45,6,80,92))))

print(tuple(map(lambda a: a%2 !=0,int(input("Enter number :")))))  #ye yha kam nhi karega becoz ye iterable nhi ha

def func():
    print("abc")
    yield 18
print(func())
# out=func()
# print("function out value: ",out)

def func():
  print("abc")
  return 1
  print("rohan")   #this will never execute becoz first return hi function se bahar nikal dega.
  return 2
print(func())
print(func())

def func():
  print("abc")
  yield 1
  print("rohan")
  print("rohan")
  yield 2
  print("rohan2")

  yield 3
  print("rohan3")


print("calling:",func())
gen=func()
print(gen) # ye only memory address dega
print("1:",next(gen))
print("2:",next(gen)) # error dega iteration ke value nhi hai
print("3:",next(gen))

def infite_value():
  n=1
  while(True):
    return n

    n+=1
print(infite_value()) # function will run from always first line
print(infite_value())

def infite_value():
  n=1
  while(True):
    yield n
    n+=1
print(infite_value())
gen=infite_value()
print(next(gen))
print(next(infite_value()))
print(infite_value())
print(next(infite_value()))
print(next(gen))
print(gen)

"""- Generator:-
- generator is kind of function
- which is generats values infintiy without loading the camplete in memory
- function should have YIELD  keyword
- lazy function
"""